spark:
  master: "yarn"
  app:
    name: "Repo1App"
    settings:
      executorMemory: "4g"
      driverMemory: "2g"
      cores: 4
database:
  url: "jdbc:mysql://localhost:3306/repo1db"
  user: "repo1user"
  password: "repo1password"
